server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/compras?useSSL=false&useTimezone=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: developer2023
  devtools:
    restart:
      additional-exclude: logs/**
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
        show_sql: false
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE

#Cache https://docs.oracle.com/javaee/7/api/javax/persistence/SharedCacheMode.html

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    org:
      hibernate:
        cache: debug
        SQL: debug
